### ISSUE TITLE
TypeError: Failed to parse URL from ./sax-wasm.wasm

### ISSUE THREAD

**Issue by brymer-meneses** [justinwilaby/svg-path-interpolator#4]
I tried running the example from the readme, and I got this error. I'm using node, however I rolled back to version 0.2.5 and everything seems to be working fine.

I even tried, the absolute path, `./node_modules/svg-path-interpolator/lib/sax-wasm/lib/sax-wasm.wasm`, and still got the error.

**Comment by kgoedecke** [comment]
I'm also curious how to get this working with Node.

**Comment by justinwilaby** [comment]
I'm not seeing an issue on my end. Have you tried using the [example in the repo](https://github.com/justinwilaby/svg-path-interpolator/blob/master/examples/index.html)?
